theme: jekyll-theme-minimal
author: Şaziye Betül Özateş
title: Şaziye Betül Özateş
description: Post-doctoral researcher @ KUIS-AI
social-network-links:
  email: "bozates@ku.edu.tr"
  github: sb-b
  google-scholar: "https://scholar.google.com/citations?user=EAlmj9yYJP0C&hl=en&oi=ao"
logo: "ozate.png"
