theme: jekyll-theme-minimal
author: Şaziye Betül Özateş
title: Şaziye Betül Özateş
description: Assistant Professor @ DSAI BOUN
email: "saziye.ozates@boun.edu.tr"
logo: "pp.jpg"
hover_logo: "kids.jpg"

