theme: jekyll-theme-minimal
author: Şaziye Betül Özateş
title: Şaziye Betül Özateş
description: Assistant Professor @ [DSAI BOUN](https://dsai.boun.edu.tr/)
email: "bozates@ku.edu.tr"
logo: "ozates.png"

