theme: jekyll-theme-minimal
title: Şaziye Betül Özateş
description: Post-doctoral researcher @ KUIS-AI
social-network-links:
  email: "bozates at ku.edu.tr"
  github: sb-b
  google-scholar: https://scholar.google.com/citations?user=EAlmj9yYJP0C&hl=en&oi=ao
